sgrna.symbol.plot <- function(x,
                              y,
                              size,
                              fdr,
                              threshold = 0.25,
                              col1      = 2,
                              col2      = "gray70",
                              xlab      = "gene id",
                              ylab      = "significance (-log2(pos score))",
                              labels    = "")
    {
        symbols(x       = x,
                y       = y,
                circles = size,
                inches  = 1/5,
                add     = FALSE,
                fg      = col2,
                bg      = col2,
                xaxs    = "i",
                yaxs    = "i",
                xlab    = xlab,
                ylab    = ylab)
        symbols(x       = x[fdr < threshold],
                y       = y[fdr < threshold],
                circles = size[fdr < threshold],
                inches  = 1/5,
                add     = TRUE,
                fg      = "gray20",
                bg      = col1,
                xaxs    = "i",
                yaxs    = "i",
                xaxt    = "n",
                yaxt    = "n")
        text(x          = x[fdr < threshold],
             y          = y[fdr < threshold],
             labels     = labels[fdr < threshold],
             pos        = 4,
             cex        = 0.6)
    }
